name: BridgeDuels
version: '${project.version}'
main: matthewadev.bridgeduels.BridgeDuels
api-version: 1.8.9
description: Bridge Duels
commands:
  startgame:
    description: starts
  setTeam:
    description: set team for player
  win:
    description: win
  winround:
    description: win the round